/* made by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreParsec.framework/CoreParsec
 */

@interface _CPNetworkTimingData : PBCodable <NSSecureCoding, _CPNetworkTimingData> {
    bool  _QUICWhitelistedDomain;
    bool  _TFOSuccess;
    double  _connectEnd;
    double  _connectStart;
    bool  _connectionRace;
    bool  _connectionReused;
    NSString * _connectionUUID;
    double  _domainLookupEnd;
    double  _domainLookupStart;
    double  _fetchStart;
    NSString * _interfaceIdentifier;
    NSString * _networkProtocolName;
    NSData * _peerAddress;
    unsigned int  _redirectCount;
    unsigned int  _redirectCountW3C;
    double  _redirectEnd;
    double  _redirectStart;
    double  _requestEnd;
    unsigned int  _requestHeaderSize;
    double  _requestStart;
    unsigned int  _responseBodyBytesDecoded;
    unsigned int  _responseBodyBytesReceived;
    double  _responseEnd;
    unsigned int  _responseHeaderSize;
    double  _responseStart;
    double  _secureConnectStart;
    _CPTCPInfo * _startTimeCounts;
    _CPTCPInfo * _stopTimeCounts;
    double  _timingDataInit;
    _CPTuscanyConnectionInfo * _tuscany;
}

@property (nonatomic) bool QUICWhitelistedDomain;
@property (nonatomic) bool TFOSuccess;
@property (nonatomic) double connectEnd;
@property (nonatomic) double connectStart;
@property (nonatomic) bool connectionRace;
@property (nonatomic) bool connectionReused;
@property (nonatomic, copy) NSString *connectionUUID;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic) double domainLookupEnd;
@property (nonatomic) double domainLookupStart;
@property (nonatomic) double fetchStart;
@property (readonly) unsigned long long hash;
@property (nonatomic, copy) NSString *interfaceIdentifier;
@property (nonatomic, readonly) NSData *jsonData;
@property (nonatomic, copy) NSString *networkProtocolName;
@property (nonatomic, copy) NSData *peerAddress;
@property (nonatomic) unsigned int redirectCount;
@property (nonatomic) unsigned int redirectCountW3C;
@property (nonatomic) double redirectEnd;
@property (nonatomic) double redirectStart;
@property (nonatomic) double requestEnd;
@property (nonatomic) unsigned int requestHeaderSize;
@property (nonatomic) double requestStart;
@property (nonatomic) unsigned int responseBodyBytesDecoded;
@property (nonatomic) unsigned int responseBodyBytesReceived;
@property (nonatomic) double responseEnd;
@property (nonatomic) unsigned int responseHeaderSize;
@property (nonatomic) double responseStart;
@property (nonatomic) double secureConnectStart;
@property (nonatomic, retain) _CPTCPInfo *startTimeCounts;
@property (nonatomic, retain) _CPTCPInfo *stopTimeCounts;
@property (readonly) Class superclass;
@property (nonatomic) double timingDataInit;
@property (nonatomic, retain) _CPTuscanyConnectionInfo *tuscany;

- (void).cxx_destruct;
- (bool)QUICWhitelistedDomain;
- (bool)TFOSuccess;
- (double)connectEnd;
- (double)connectStart;
- (bool)connectionRace;
- (bool)connectionReused;
- (id)connectionUUID;
- (id)dictionaryRepresentation;
- (double)domainLookupEnd;
- (double)domainLookupStart;
- (double)fetchStart;
- (unsigned long long)hash;
- (id)initWithDictionary:(id)arg1;
- (id)initWithJSON:(id)arg1;
- (id)interfaceIdentifier;
- (bool)isEqual:(id)arg1;
- (id)jsonData;
- (id)networkProtocolName;
- (id)peerAddress;
- (bool)readFrom:(id)arg1;
- (unsigned int)redirectCount;
- (unsigned int)redirectCountW3C;
- (double)redirectEnd;
- (double)redirectStart;
- (double)requestEnd;
- (unsigned int)requestHeaderSize;
- (double)requestStart;
- (bool)requiresQueryId;
- (unsigned int)responseBodyBytesDecoded;
- (unsigned int)responseBodyBytesReceived;
- (double)responseEnd;
- (unsigned int)responseHeaderSize;
- (double)responseStart;
- (double)secureConnectStart;
- (void)setConnectEnd:(double)arg1;
- (void)setConnectStart:(double)arg1;
- (void)setConnectionRace:(bool)arg1;
- (void)setConnectionReused:(bool)arg1;
- (void)setConnectionUUID:(id)arg1;
- (void)setDomainLookupEnd:(double)arg1;
- (void)setDomainLookupStart:(double)arg1;
- (void)setFetchStart:(double)arg1;
- (void)setInterfaceIdentifier:(id)arg1;
- (void)setNetworkProtocolName:(id)arg1;
- (void)setPeerAddress:(id)arg1;
- (void)setQUICWhitelistedDomain:(bool)arg1;
- (void)setRedirectCount:(unsigned int)arg1;
- (void)setRedirectCountW3C:(unsigned int)arg1;
- (void)setRedirectEnd:(double)arg1;
- (void)setRedirectStart:(double)arg1;
- (void)setRequestEnd:(double)arg1;
- (void)setRequestHeaderSize:(unsigned int)arg1;
- (void)setRequestStart:(double)arg1;
- (void)setResponseBodyBytesDecoded:(unsigned int)arg1;
- (void)setResponseBodyBytesReceived:(unsigned int)arg1;
- (void)setResponseEnd:(double)arg1;
- (void)setResponseHeaderSize:(unsigned int)arg1;
- (void)setResponseStart:(double)arg1;
- (void)setSecureConnectStart:(double)arg1;
- (void)setStartTimeCounts:(id)arg1;
- (void)setStopTimeCounts:(id)arg1;
- (void)setTFOSuccess:(bool)arg1;
- (void)setTimingDataInit:(double)arg1;
- (void)setTuscany:(id)arg1;
- (id)startTimeCounts;
- (id)stopTimeCounts;
- (double)timingDataInit;
- (id)tuscany;
- (void)writeTo:(id)arg1;

@end
