/* made by EzioChiu
   Image: /System/Library/PrivateFrameworks/CoreParsec.framework/CoreParsec
 */

@interface _CPSearchResultForFeedback : PBCodable <NSSecureCoding, _CPSearchResultForFeedback> {
    _CPActionItemForFeedback * _action;
    NSString * _applicationBundleIdentifier;
    unsigned long long  _blockId;
    NSString * _completedQuery;
    NSString * _correctedQuery;
    bool  _doNotFold;
    NSString * _fbr;
    NSString * _identifier;
    NSString * _intendedQuery;
    bool  _isFuzzyMatch;
    bool  _isLocalApplicationResult;
    bool  _isStaticCorrection;
    _CPStruct * _localFeatures;
    bool  _publiclyIndexable;
    _CPPunchoutForFeedback * _punchout;
    unsigned long long  _queryId;
    double  _rankingScore;
    NSString * _resultBundleId;
    NSString * _resultType;
    NSString * _sectionBundleIdentifier;
    NSString * _srf;
    int  _topHit;
    int  _type;
    NSString * _userInput;
}

@property (nonatomic, retain) _CPActionItemForFeedback *action;
@property (nonatomic, copy) NSString *applicationBundleIdentifier;
@property (nonatomic) unsigned long long blockId;
@property (nonatomic, copy) NSString *completedQuery;
@property (nonatomic, copy) NSString *correctedQuery;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic) bool doNotFold;
@property (nonatomic, copy) NSString *fbr;
@property (readonly) unsigned long long hash;
@property (nonatomic, copy) NSString *identifier;
@property (nonatomic, copy) NSString *intendedQuery;
@property (nonatomic) bool isFuzzyMatch;
@property (nonatomic) bool isLocalApplicationResult;
@property (nonatomic) bool isStaticCorrection;
@property (nonatomic, readonly) NSData *jsonData;
@property (nonatomic, retain) _CPStruct *localFeatures;
@property (nonatomic) bool publiclyIndexable;
@property (nonatomic, retain) _CPPunchoutForFeedback *punchout;
@property (nonatomic) unsigned long long queryId;
@property (nonatomic) double rankingScore;
@property (nonatomic, copy) NSString *resultBundleId;
@property (nonatomic, copy) NSString *resultType;
@property (nonatomic, copy) NSString *sectionBundleIdentifier;
@property (nonatomic, copy) NSString *srf;
@property (readonly) Class superclass;
@property (nonatomic) int topHit;
@property (nonatomic) int type;
@property (nonatomic, copy) NSString *userInput;

- (void).cxx_destruct;
- (id)action;
- (id)applicationBundleIdentifier;
- (unsigned long long)blockId;
- (id)completedQuery;
- (id)correctedQuery;
- (id)dictionaryRepresentation;
- (bool)doNotFold;
- (id)fbr;
- (id)feedbackJSON;
- (unsigned long long)hash;
- (id)identifier;
- (id)initWithDictionary:(id)arg1;
- (id)initWithFacade:(id)arg1;
- (id)initWithJSON:(id)arg1;
- (id)intendedQuery;
- (bool)isEqual:(id)arg1;
- (bool)isFuzzyMatch;
- (bool)isLocalApplicationResult;
- (bool)isStaticCorrection;
- (id)jsonData;
- (id)localFeatures;
- (bool)publiclyIndexable;
- (id)punchout;
- (unsigned long long)queryId;
- (double)rankingScore;
- (bool)readFrom:(id)arg1;
- (id)resultBundleId;
- (id)resultType;
- (id)sectionBundleIdentifier;
- (void)setAction:(id)arg1;
- (void)setApplicationBundleIdentifier:(id)arg1;
- (void)setBlockId:(unsigned long long)arg1;
- (void)setCompletedQuery:(id)arg1;
- (void)setCorrectedQuery:(id)arg1;
- (void)setDoNotFold:(bool)arg1;
- (void)setFbr:(id)arg1;
- (void)setIdentifier:(id)arg1;
- (void)setIntendedQuery:(id)arg1;
- (void)setIsFuzzyMatch:(bool)arg1;
- (void)setIsLocalApplicationResult:(bool)arg1;
- (void)setIsStaticCorrection:(bool)arg1;
- (void)setLocalFeatures:(id)arg1;
- (void)setPubliclyIndexable:(bool)arg1;
- (void)setPunchout:(id)arg1;
- (void)setQueryId:(unsigned long long)arg1;
- (void)setRankingScore:(double)arg1;
- (void)setResultBundleId:(id)arg1;
- (void)setResultType:(id)arg1;
- (void)setSectionBundleIdentifier:(id)arg1;
- (void)setSrf:(id)arg1;
- (void)setTopHit:(int)arg1;
- (void)setType:(int)arg1;
- (void)setUserInput:(id)arg1;
- (id)srf;
- (int)topHit;
- (int)type;
- (id)userInput;
- (void)writeTo:(id)arg1;

@end
