/* made by EzioChiu
   Image: /System/Library/PrivateFrameworks/NanoMusicSync.framework/NanoMusicSync
 */

@interface NMSMediaPinningManager : NSObject {
    NSArray * _cachedAlbumIdentifiers;
    NSArray * _cachedPlaylistIdentifiers;
    NSObject<OS_dispatch_queue> * _internalQueue;
    NMSMediaItemGroupIterator * _musicGroupIterator;
    bool  _pinnedPlaylistsValidated;
    NMSPodcastSizeCache * _podcastSizeCache;
    NMSMediaItemGroupIterator * _podcastsGroupIterator;
    NMSMediaQuotaManager * _quotaManager;
    NMSyncDefaults * _sharedDefaults;
    bool  _workoutPlaylistValidated;
}

@property (nonatomic, readonly) NSArray *addedItems;
@property (nonatomic, readonly) NSArray *addedMusicItems;
@property (nonatomic, readonly) NSSet *addedPodcastEpisodes;
@property (nonatomic, readonly) NSArray *addedPodcastEpisodesArray;
@property (nonatomic, readonly) NSArray *addedPodcastsItems;
@property (nonatomic, readonly) NSArray *addedSongsArray;
@property (nonatomic, readonly) NSArray *albumIdentifiers;
@property (nonatomic, retain) NMSMediaItemGroupIterator *musicGroupIterator;
@property (nonatomic, readonly) NSArray *offPowerEligibleSongsList;
@property (nonatomic, readonly) NSArray *onlyOnPowerSongsList;
@property (nonatomic, readonly) NSArray *pinnedAlbums;
@property (nonatomic, readonly) NSArray *pinnedPlaylists;
@property (nonatomic, readonly) NSSet *pinnedPodcasts;
@property (nonatomic) bool pinnedPodcastsAreUserSet;
@property (nonatomic, readonly) NSArray *playlistIdentifiers;
@property (nonatomic, retain) NSNumber *podcastsAssetSyncLimit;
@property (nonatomic, retain) NMSMediaItemGroupIterator *podcastsGroupIterator;
@property (nonatomic, retain) NMSMediaQuotaManager *quotaManager;
@property (nonatomic, retain) NSNumber *workoutPlaylistID;

+ (id)_cachedAlbumIdentifiersFilePath;
+ (id)_cachedIdentifiersDirectoryPath;
+ (id)_cachedPlaylistIdentifiersFilePath;
+ (id)_fetchMusicRecommendations;
+ (void)_persistNewClientToken;
+ (id)_tokenForInstance:(id)arg1;
+ (unsigned long long)mediaStorageSizeForCurrentWatch;
+ (bool)playlistPIDValidForPinning:(id)arg1;
+ (id)sharedManager;

- (void).cxx_destruct;
- (void)_handleMediaLibraryEntitiesAddedOrRemovedNotification:(id)arg1;
- (void)_handleMusicPinningSelectionsDidChangeNotification:(id)arg1;
- (void)_handlePairedDeviceDidBecomeActiveNotification:(id)arg1;
- (void)_handlePinningSettingsDidChangeNotification:(id)arg1;
- (void)_handlePodcastSizeCacheDidUpdateNotification:(id)arg1;
- (void)_handlePodcastSizeInfoDidChangeNotification:(id)arg1;
- (void)_handlePodcastsPinningSelectionsDidChangeNotification:(id)arg1;
- (void)_handleRecommendationLibraryContentsDidChangeNotification:(id)arg1;
- (void)_handleRecommendationSelectionsDidChangeNotification:(id)arg1;
- (void)_handleRecommendationsDidUpdateNotification:(id)arg1;
- (void)_invalidateAddedItemsCache;
- (void)_invalidateMusicCache;
- (void)_invalidatePodcastsCache;
- (bool)_isAlbumPinned:(id)arg1;
- (bool)_isPlaylistPinned:(id)arg1;
- (void)_notePinningSettingsChangedLocally;
- (unsigned int)_pairedWatchVersion;
- (void)_refreshAlbumIdentifiersWithPath:(id)arg1;
- (void)_refreshPlaylistIdentifiersWithPath:(id)arg1;
- (void)_setWorkoutPlaylistID:(id)arg1;
- (void)_updateWorkoutSettingsPlaylistPIDTo:(id)arg1;
- (id)addedItems;
- (id)addedItemsWithMediaTypes:(unsigned int)arg1;
- (id)addedMusicItems;
- (id)addedPodcastEpisodes;
- (id)addedPodcastEpisodesArray;
- (id)addedPodcastsItems;
- (id)addedSongsArray;
- (unsigned long long)addedSongsSize;
- (id)albumIdentifiers;
- (unsigned long long)downloadOrderForPodcastWithFeedURL:(id)arg1;
- (unsigned long long)gizmoDownloadOrderForPodcastWithIdentifiers:(id)arg1;
- (id)init;
- (void)invalidateCache;
- (void)invalidateMusicCache;
- (void)invalidatePodcastsCache;
- (bool)isAlbumPinned:(id)arg1;
- (bool)isItemGroupWithinQuota:(id)arg1;
- (bool)isPlaylistPinned:(id)arg1;
- (bool)isPodcastPinned:(id)arg1;
- (bool)isPodcastWithFeedURLPinned:(id)arg1;
- (bool)isPodcastWithIdentifiersPinned:(id)arg1;
- (id)itemGroupForIdentifiers:(id)arg1;
- (id)musicGroupIterator;
- (unsigned long long)nominatedSongsSize;
- (id)offPowerEligibleSongsList;
- (id)onlyOnPowerSongsList;
- (void)pinAlbum:(id)arg1;
- (void)pinPlaylist:(id)arg1;
- (void)pinPodcast:(id)arg1;
- (void)pinPodcastWithFeedURL:(id)arg1;
- (void)pinPodcastWithIdentifiers:(id)arg1;
- (id)pinnedAlbums;
- (id)pinnedPlaylists;
- (id)pinnedPodcasts;
- (bool)pinnedPodcastsAreUserSet;
- (id)playlistIdentifiers;
- (id)podcastsAssetSyncLimit;
- (id)podcastsGroupIterator;
- (id)quotaManager;
- (void)removePodcastWithFeedURL:(id)arg1;
- (void)removePodcastWithIdentifiers:(id)arg1;
- (void)replacePodcastIdentifiers:(id)arg1 withIdentifiers:(id)arg2;
- (void)setGizmoDownloadOrder:(unsigned long long)arg1 forPodcastWithFeedURL:(id)arg2;
- (void)setGizmoDownloadOrder:(unsigned long long)arg1 forPodcastWithIdentifiers:(id)arg2;
- (void)setListenNowEpisodePIDs:(id)arg1;
- (void)setListenNowPodcastFeedURLs:(id)arg1;
- (void)setListenNowPodcastIdentifiers:(id)arg1;
- (void)setMusicGroupIterator:(id)arg1;
- (void)setPinnedPodcastsAreUserSet:(bool)arg1;
- (void)setPodcastsAssetSyncLimit:(id)arg1;
- (void)setPodcastsGroupIterator:(id)arg1;
- (void)setQuotaManager:(id)arg1;
- (void)setWorkoutPlaylistID:(id)arg1;
- (void)unpinAlbum:(id)arg1;
- (void)unpinPlaylist:(id)arg1;
- (void)unpinPodcast:(id)arg1;
- (void)unpinPodcastWithFeedURL:(id)arg1;
- (void)unpinPodcastWithIdentifiers:(id)arg1;
- (id)workoutPlaylistID;

@end
