/* made by EzioChiu
   Image: /System/Library/PrivateFrameworks/UserNotificationsUIKit.framework/UserNotificationsUIKit
 */

@interface NCNotificationContentView : UIView <MTVibrantStylingProviderObserving, MTVibrantStylingRequiring, PLContentSizeCategoryAdjusting, UITextViewDelegate> {
    UIView * _accessoryView;
    bool  _adjustsFontForContentSizeCategory;
    struct UIEdgeInsets { 
        double top; 
        double left; 
        double bottom; 
        double right; 
    }  _contentInsets;
    UIView * _contentView;
    <NCNotificationContentViewDelegate> * _delegate;
    NSStringDrawingContext * _drawingContext;
    BSUIFontProvider * _fontProvider;
    long long  _lookStyle;
    NSString * _preferredContentSizeCategory;
    UILabel * _primaryLabel;
    UILabel * _primarySubtitleLabel;
    UITextView * _secondaryTextView;
    UILabel * _summaryLabel;
    UIImageView * _thumbnailImageView;
    MTVibrantStylingProvider * _vibrantStylingProvider;
    NSMutableDictionary * _widthToFontToStringToMeasuredNumLines;
}

@property (nonatomic, retain) UIView *accessoryView;
@property (nonatomic) bool adjustsFontForContentSizeCategory;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <NCNotificationContentViewDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (getter=_fontProvider, setter=_setFontProvider:, nonatomic, retain) BSUIFontProvider *fontProvider;
@property (readonly) unsigned long long hash;
@property (nonatomic) unsigned long long messageNumberOfLines;
@property (nonatomic, copy) NSString *preferredContentSizeCategory;
@property (getter=_primaryLabel, setter=_setPrimaryLabel:, nonatomic, retain) UILabel *primaryLabel;
@property (getter=_primarySubtitleLabel, setter=_setPrimarySubtitleLabel:, nonatomic, retain) UILabel *primarySubtitleLabel;
@property (nonatomic, retain) NSString *primarySubtitleText;
@property (nonatomic, retain) NSString *primaryText;
@property (nonatomic, retain) NSString *secondaryText;
@property (getter=_secondaryTextView, setter=_setSecondaryTextView:, nonatomic, retain) UITextView *secondaryTextView;
@property (getter=_summaryLabel, setter=_setSummaryLabel:, nonatomic, retain) UILabel *summaryLabel;
@property (nonatomic, retain) NSString *summaryText;
@property (readonly) Class superclass;
@property (nonatomic, retain) UIImage *thumbnail;
@property (nonatomic, retain) MTVibrantStylingProvider *vibrantStylingProvider;

- (void).cxx_destruct;
- (long long)_cachedNumberOfMeasuredLinesForText:(id)arg1 withFont:(id)arg2 forWidth:(double)arg3;
- (void)_clearCacheForFont:(id)arg1;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })_contentInsets;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })_contentInsetsForLongLook;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })_contentInsetsForShortLook;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })_contentInsetsForStyle:(long long)arg1;
- (id)_fontProvider;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })_frameForThumbnailInRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)_invalidateNumberOfLinesCache;
- (id)_lazyPrimaryLabel;
- (id)_lazyPrimarySubtitleLabel;
- (id)_lazySecondaryTextView;
- (id)_lazySummaryLabel;
- (id)_lazyThumbnailImageView;
- (id)_newPrimaryLabel;
- (id)_newSecondaryTextView;
- (id)_newSummaryLabel;
- (long long)_numberOfMeasuredLinesForText:(id)arg1 withFont:(id)arg2 forSize:(struct CGSize { double x1; double x2; })arg3;
- (id)_primaryLabel;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })_primaryLabelBoundsForSize:(struct CGSize { double x1; double x2; })arg1 withContentInsets:(struct UIEdgeInsets { double x1; double x2; double x3; double x4; })arg2 andNumberOfLines:(double)arg3;
- (id)_primarySubtitleLabel;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })_primarySubtitleLabelBoundsForSize:(struct CGSize { double x1; double x2; })arg1 withContentInsets:(struct UIEdgeInsets { double x1; double x2; double x3; double x4; })arg2 andNumberOfLines:(double)arg3;
- (double)_primarySubtitleTextBaselineOffsetForCurrentStyle;
- (long long)_primarySubtitleTextMeasuredNumberOfLinesForWidth:(double)arg1;
- (long long)_primarySubtitleTextNumberOfLinesWithMeasuredNumberOfLines:(long long)arg1;
- (double)_primaryTextBaselineOffsetWithBaseValue:(double)arg1;
- (long long)_primaryTextMeasuredNumberOfLinesForWidth:(double)arg1;
- (long long)_primaryTextNumberOfLinesWithMeasuredNumberOfLines:(long long)arg1;
- (double)_secondaryTextBaselineOffsetForCurrentStyle;
- (double)_secondaryTextBaselineOffsetFromBottomWithBaseValue:(double)arg1;
- (double)_secondaryTextBaselineOffsetWithBaseValue:(double)arg1;
- (long long)_secondaryTextMeasuredNumberOfLinesForWidth:(double)arg1;
- (unsigned long long)_secondaryTextNumberOfLines;
- (long long)_secondaryTextNumberOfLinesWithMeasuredNumberOfLines:(long long)arg1;
- (id)_secondaryTextView;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })_secondaryTextViewBoundsForSize:(struct CGSize { double x1; double x2; })arg1 withContentInsets:(struct UIEdgeInsets { double x1; double x2; double x3; double x4; })arg2 andNumberOfLines:(double)arg3;
- (void)_setFontProvider:(id)arg1;
- (void)_setPrimaryLabel:(id)arg1;
- (void)_setPrimarySubtitleLabel:(id)arg1;
- (void)_setSecondaryTextNumberOfLines:(unsigned long long)arg1;
- (void)_setSecondaryTextView:(id)arg1;
- (void)_setSummaryLabel:(id)arg1;
- (struct CGSize { double x1; double x2; })_sizeThatFits:(struct CGSize { double x1; double x2; })arg1 withContentInsets:(struct UIEdgeInsets { double x1; double x2; double x3; double x4; })arg2;
- (id)_summaryLabel;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })_summaryLabelBoundsForSize:(struct CGSize { double x1; double x2; })arg1 withContentInsets:(struct UIEdgeInsets { double x1; double x2; double x3; double x4; })arg2 andNumberOfLines:(double)arg3;
- (double)_summaryTextBaselineOffsetForCurrentStyle;
- (double)_summaryTextBaselineOffsetWithBaseValue:(double)arg1;
- (long long)_summaryTextMeasuredNumberOfLinesForWidth:(double)arg1;
- (long long)_summaryTextNumberOfLinesWithMeasuredNumberOfLines:(long long)arg1;
- (void)_updateFontForSecondaryTextView:(id)arg1 withStyle:(long long)arg2;
- (void)_updateStyleForPrimaryLabel:(id)arg1 withStyle:(long long)arg2;
- (void)_updateStyleForSecondaryTextView:(id)arg1 withStyle:(long long)arg2;
- (void)_updateStyleForSummaryLabel:(id)arg1 withStyle:(long long)arg2;
- (void)_updateTextAttributesForLabel:(id)arg1;
- (void)_updateTextAttributesForPrimaryLabel:(id)arg1 withStyle:(long long)arg2;
- (void)_updateTextAttributesForSummaryLabel:(id)arg1 withStyle:(long long)arg2;
- (id)accessoryView;
- (bool)adjustForContentSizeCategoryChange;
- (bool)adjustsFontForContentSizeCategory;
- (id)debugDescription;
- (id)delegate;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)initWithStyle:(long long)arg1;
- (void)layoutSubviews;
- (unsigned long long)messageNumberOfLines;
- (void)nc_performDeferredActionsIfNeeded;
- (id)preferredContentSizeCategory;
- (id)primarySubtitleText;
- (id)primaryText;
- (id)secondaryText;
- (void)setAccessoryView:(id)arg1;
- (void)setAdjustsFontForContentSizeCategory:(bool)arg1;
- (void)setDelegate:(id)arg1;
- (void)setMessageNumberOfLines:(unsigned long long)arg1;
- (void)setPreferredContentSizeCategory:(id)arg1;
- (void)setPrimarySubtitleText:(id)arg1;
- (void)setPrimaryText:(id)arg1;
- (void)setSecondaryText:(id)arg1;
- (void)setSummaryText:(id)arg1;
- (void)setThumbnail:(id)arg1;
- (void)setVibrantStylingProvider:(id)arg1;
- (struct CGSize { double x1; double x2; })sizeThatFits:(struct CGSize { double x1; double x2; })arg1;
- (id)summaryText;
- (bool)textView:(id)arg1 shouldInteractWithURL:(id)arg2 inRange:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg3 interaction:(long long)arg4;
- (id)thumbnail;
- (void)traitCollectionDidChange:(id)arg1;
- (void)vibrantStylingDidChangeForProvider:(id)arg1;
- (id)vibrantStylingProvider;

@end
