/* made by EzioChiu
   Image: /System/Library/PrivateFrameworks/VoiceShortcutsUI.framework/VoiceShortcutsUI
 */

@interface VCUIManageVoiceShortcutViewController : UIViewController <SUICFlamesViewDelegate, UITextFieldDelegate, VCUIAlternativeTranscriptionsViewDelegate, VCUIPhraseRecognizerDelegate> {
    <VCActionDonation> * _actionDonation;
    NSArray * _alternativeTranscriptions;
    VCUIAlternativeTranscriptionsView * _alternativeTranscriptionsView;
    bool  _animatingHeadlineView;
    UILabel * _buttonDescriptionLabel;
    unsigned long long  _clientRequests;
    UIView * _contentView;
    VCVoiceShortcut * _createdVoiceShortcut;
    <VCUIManageVoiceShortcutViewControllerDelegate> * _delegate;
    UIButton * _deleteButton;
    bool  _dismissOnClientRequestsCompletion;
    VCUIActionDonationDetailView * _donationDetailView;
    UIButton * _editButton;
    SUICFlamesView * _flamesView;
    VCUIHeadlineView * _headlineView;
    NSLayoutConstraint * _headlineViewAnimationBeginConstraint;
    NSLayoutConstraint * _headlineViewAnimationCompleteConstraint;
    NSString * _latestTranscription;
    NSLayoutConstraint * _leadingConstraint;
    NSString * _originalVoiceShortcutPhrase;
    NSLayoutConstraint * _pageInAnimationBeginConstraint;
    NSLayoutConstraint * _pageInAnimationCompleteConstraint;
    VCUIPhraseRecognizer * _phraseRecognizer;
    UILabel * _phraseRestrictedLabel;
    VCUIRecordButton * _recordButton;
    UIButton * _rerecordPhraseButton;
    bool  _speechStarted;
    NSLayoutConstraint * _topConstraint;
    NSLayoutConstraint * _trailingConstraint;
    UIButton * _typeToSiriButton;
    bool  _typeToSiriEnabled;
    UILabel * _typeToSiriLabel;
    UITextField * _typeToSiriTextField;
    UIView * _typeToSiriTextFieldBottomBorder;
    UIView * _typeToSiriTextFieldTopBorder;
    NSArray * _validationResult;
    VCVoiceShortcut * _voiceShortcut;
    VCVoiceShortcutClient * _voiceShortcutClient;
}

@property (nonatomic, readonly) <VCActionDonation> *actionDonation;
@property (nonatomic, retain) NSArray *alternativeTranscriptions;
@property (nonatomic) VCUIAlternativeTranscriptionsView *alternativeTranscriptionsView;
@property (nonatomic) bool animatingHeadlineView;
@property (nonatomic, retain) UILabel *buttonDescriptionLabel;
@property (nonatomic) unsigned long long clientRequests;
@property (nonatomic, retain) UIView *contentView;
@property (nonatomic, retain) VCVoiceShortcut *createdVoiceShortcut;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <VCUIManageVoiceShortcutViewControllerDelegate> *delegate;
@property (nonatomic, retain) UIButton *deleteButton;
@property (readonly, copy) NSString *description;
@property (nonatomic) bool dismissOnClientRequestsCompletion;
@property (nonatomic, retain) VCUIActionDonationDetailView *donationDetailView;
@property (nonatomic, retain) UIButton *editButton;
@property (nonatomic, retain) SUICFlamesView *flamesView;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) VCUIHeadlineView *headlineView;
@property (nonatomic, retain) NSLayoutConstraint *headlineViewAnimationBeginConstraint;
@property (nonatomic, retain) NSLayoutConstraint *headlineViewAnimationCompleteConstraint;
@property (nonatomic, retain) NSString *latestTranscription;
@property (nonatomic, retain) NSLayoutConstraint *leadingConstraint;
@property (nonatomic, retain) NSString *originalVoiceShortcutPhrase;
@property (nonatomic, retain) NSLayoutConstraint *pageInAnimationBeginConstraint;
@property (nonatomic, retain) NSLayoutConstraint *pageInAnimationCompleteConstraint;
@property (nonatomic, retain) VCUIPhraseRecognizer *phraseRecognizer;
@property (nonatomic, retain) UILabel *phraseRestrictedLabel;
@property (nonatomic, retain) VCUIRecordButton *recordButton;
@property (nonatomic, retain) UIButton *rerecordPhraseButton;
@property (nonatomic) bool speechStarted;
@property (readonly) Class superclass;
@property (nonatomic, retain) NSLayoutConstraint *topConstraint;
@property (nonatomic, retain) NSLayoutConstraint *trailingConstraint;
@property (nonatomic, retain) UIButton *typeToSiriButton;
@property (nonatomic) bool typeToSiriEnabled;
@property (nonatomic, retain) UILabel *typeToSiriLabel;
@property (nonatomic, retain) UITextField *typeToSiriTextField;
@property (nonatomic, retain) UIView *typeToSiriTextFieldBottomBorder;
@property (nonatomic, retain) UIView *typeToSiriTextFieldTopBorder;
@property (nonatomic, retain) NSArray *validationResult;
@property (nonatomic, retain) VCVoiceShortcut *voiceShortcut;
@property (nonatomic, readonly) VCVoiceShortcutClient *voiceShortcutClient;

+ (void)initialize;
+ (void)setVoiceRecognitionOverrideWithAudioFileAtPath:(id)arg1;

- (void).cxx_destruct;
- (id)actionDonation;
- (void)addEditButton;
- (void)addRerecordPhraseButton;
- (id)alertControllerForError:(id)arg1;
- (id)alternativeTranscriptions;
- (id)alternativeTranscriptionsView;
- (void)alternativeTranscriptionsView:(id)arg1 didSelectTranscription:(id)arg2;
- (void)animatePageIn;
- (bool)animatingHeadlineView;
- (float)audioLevelForFlamesView:(id)arg1;
- (id)buttonDescriptionLabel;
- (unsigned long long)clientRequests;
- (id)contentView;
- (void)createOrUpdateCurrentVoiceShortcut;
- (void)createShortcut;
- (void)createShortcutAndDismissOnSuccess:(bool)arg1;
- (id)createdVoiceShortcut;
- (id)delegate;
- (id)deleteButton;
- (void)didTapCancel;
- (void)didTapDelete;
- (void)didTapDone;
- (void)didTapEdit;
- (void)didTapEditShortcut:(id)arg1;
- (void)didTapRecord;
- (void)didTapTypeToSiri;
- (bool)dismiss;
- (bool)dismissOnClientRequestsCompletion;
- (void)dismissWhenComplete;
- (id)donationDetailView;
- (id)editButton;
- (id)existingIdentifierFromError:(id)arg1;
- (id)filterAlternativeTranscriptions:(id)arg1 withValidationResult:(id)arg2 bestTranscription:(id)arg3;
- (void)finishedClientRequest;
- (id)flamesView;
- (id)headlineView;
- (id)headlineViewAnimationBeginConstraint;
- (id)headlineViewAnimationCompleteConstraint;
- (id)initWithActionDonation:(id)arg1 voiceShortcutClient:(id)arg2;
- (id)initWithVoiceShortcut:(id)arg1 voiceShortcutClient:(id)arg2;
- (id)latestTranscription;
- (id)leadingConstraint;
- (void)loadView;
- (id)originalVoiceShortcutPhrase;
- (id)pageInAnimationBeginConstraint;
- (id)pageInAnimationCompleteConstraint;
- (id)phraseRecognizer;
- (void)phraseRecognizer:(id)arg1 availabilityDidChange:(bool)arg2;
- (void)phraseRecognizer:(id)arg1 didReceiveFinalTranscription:(id)arg2 alternativeTranscriptions:(id)arg3;
- (void)phraseRecognizer:(id)arg1 didReceiveHypothesizedTranscription:(id)arg2;
- (void)phraseRecognizerDidStartRecording:(id)arg1 successfully:(bool)arg2 error:(id)arg3;
- (void)phraseRecognizerDidStopRecording:(id)arg1 withError:(id)arg2;
- (id)phraseRestrictedLabel;
- (id)recordButton;
- (id)rerecordPhraseButton;
- (void)resetViewToInitialState;
- (void)setAlternativeTranscriptions:(id)arg1;
- (void)setAlternativeTranscriptionsView:(id)arg1;
- (void)setAnimatingHeadlineView:(bool)arg1;
- (void)setButtonDescriptionLabel:(id)arg1;
- (void)setClientRequests:(unsigned long long)arg1;
- (void)setContentView:(id)arg1;
- (void)setCreatedVoiceShortcut:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setDeleteButton:(id)arg1;
- (void)setDismissOnClientRequestsCompletion:(bool)arg1;
- (void)setDonationDetailView:(id)arg1;
- (void)setEditButton:(id)arg1;
- (void)setFlamesView:(id)arg1;
- (void)setHeadlineView:(id)arg1;
- (void)setHeadlineViewAnimationBeginConstraint:(id)arg1;
- (void)setHeadlineViewAnimationCompleteConstraint:(id)arg1;
- (void)setLatestTranscription:(id)arg1;
- (void)setLeadingConstraint:(id)arg1;
- (void)setOriginalVoiceShortcutPhrase:(id)arg1;
- (void)setPageInAnimationBeginConstraint:(id)arg1;
- (void)setPageInAnimationCompleteConstraint:(id)arg1;
- (void)setPhraseRecognizer:(id)arg1;
- (void)setPhraseRestrictedLabel:(id)arg1;
- (void)setRecordButton:(id)arg1;
- (void)setRerecordPhraseButton:(id)arg1;
- (void)setSpeechStarted:(bool)arg1;
- (void)setTopConstraint:(id)arg1;
- (void)setTrailingConstraint:(id)arg1;
- (void)setTypeToSiriButton:(id)arg1;
- (void)setTypeToSiriEnabled:(bool)arg1;
- (void)setTypeToSiriLabel:(id)arg1;
- (void)setTypeToSiriTextField:(id)arg1;
- (void)setTypeToSiriTextFieldBottomBorder:(id)arg1;
- (void)setTypeToSiriTextFieldTopBorder:(id)arg1;
- (void)setValidationResult:(id)arg1;
- (void)setVoiceShortcut:(id)arg1;
- (void)showPhraseSuggestion;
- (void)showPhraseSuggestionIfNeeded:(id)arg1;
- (bool)speechStarted;
- (void)startRecording;
- (void)startedClientRequest;
- (void)textFieldDidChange:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1 reason:(long long)arg2;
- (bool)textFieldShouldReturn:(id)arg1;
- (id)topConstraint;
- (id)trailingConstraint;
- (void)traitCollectionDidChange:(id)arg1;
- (id)typeToSiriButton;
- (bool)typeToSiriEnabled;
- (id)typeToSiriLabel;
- (id)typeToSiriTextField;
- (id)typeToSiriTextFieldBottomBorder;
- (id)typeToSiriTextFieldTopBorder;
- (void)updateDoneButton;
- (void)updateForPhraseRecognitionComplete:(id)arg1;
- (void)updateForPhraseRecognizerAvailability;
- (void)updateForTypingPhrase;
- (void)updateLayout;
- (void)updatePhraseRestrictedText:(id)arg1;
- (void)validateTranscription:(id)arg1 alternativeTranscriptions:(id)arg2;
- (id)validationResult;
- (id)validationResultForPhrase:(id)arg1 fromResults:(id)arg2;
- (void)viewWillAppear:(bool)arg1;
- (void)viewWillDisappear:(bool)arg1;
- (void)viewWillTransitionToSize:(struct CGSize { double x1; double x2; })arg1 withTransitionCoordinator:(id)arg2;
- (bool)voiceRecordButtonHidden;
- (id)voiceShortcut;
- (id)voiceShortcutClient;

@end
