/* made by EzioChiu
   Image: /System/Library/PrivateFrameworks/ScreenTimeUI.framework/ScreenTimeUI
 */

@interface STUsageGraphView : UIView <UIGestureRecognizerDelegate> {
    STUsageItem * _aggregateUsageItem;
    UILayoutGuide * _barSectionLayoutGuide;
    NSArray * _barViewHeightConstraints;
    NSArray * _barViews;
    STDeviceBedtime * _bedtime;
    UILayoutGuide * _bedtimeFieldLayoutGuide;
    NSArray * _bedtimeFields;
    UILayoutGuide * _graphLayoutGuide;
    unsigned long long  _higherResolutionCalendarUnit;
    UIImageView * _horizontalBaseline;
    UILayoutGuide * _labelSectionLayoutGuide;
    UIView * _paddleConnectorView;
    STPaddleView * _paddleView;
    NSLayoutConstraint * _paddleViewCenterXConstraint;
    NSLayoutConstraint * _paddleViewConnectorCenterXConstraint;
    STBarView * _selectedBarView;
    NSDate * _startDate;
    unsigned long long  _timePeriod;
    unsigned long long  _timePeriodUnit;
    UIView * _titleView;
    NSArray * _usageItems;
    NSArray * _verticalDividers;
    NSArray * _verticalLayoutGuides;
    NSLayoutConstraint * _weeklyAverageHeightConstraint;
    UILayoutGuide * _weeklyAverageLayoutGuide;
    UIImageView * _weeklyAverageLine;
    NSLayoutConstraint * _weeklyAverageTrailingConstraint;
}

@property (nonatomic, retain) STUsageItem *aggregateUsageItem;
@property (nonatomic, retain) UILayoutGuide *barSectionLayoutGuide;
@property (nonatomic, copy) NSArray *barViewHeightConstraints;
@property (nonatomic, copy) NSArray *barViews;
@property (nonatomic, copy) STDeviceBedtime *bedtime;
@property (nonatomic, retain) UILayoutGuide *bedtimeFieldLayoutGuide;
@property (nonatomic, copy) NSArray *bedtimeFields;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) UILayoutGuide *graphLayoutGuide;
@property (readonly) unsigned long long hash;
@property (nonatomic) unsigned long long higherResolutionCalendarUnit;
@property (nonatomic, retain) UIImageView *horizontalBaseline;
@property (nonatomic, retain) UILayoutGuide *labelSectionLayoutGuide;
@property (nonatomic, retain) UIView *paddleConnectorView;
@property (nonatomic, retain) STPaddleView *paddleView;
@property (nonatomic, retain) NSLayoutConstraint *paddleViewCenterXConstraint;
@property (nonatomic, retain) NSLayoutConstraint *paddleViewConnectorCenterXConstraint;
@property (nonatomic, retain) STBarView *selectedBarView;
@property (nonatomic, retain) NSDate *startDate;
@property (readonly) Class superclass;
@property (nonatomic) unsigned long long timePeriod;
@property (nonatomic) unsigned long long timePeriodUnit;
@property (nonatomic, readonly) UIView *titleView;
@property (nonatomic, copy) NSArray *usageItems;
@property (nonatomic, copy) NSArray *verticalDividers;
@property (nonatomic, copy) NSArray *verticalLayoutGuides;
@property (nonatomic, retain) NSLayoutConstraint *weeklyAverageHeightConstraint;
@property (nonatomic, retain) UILayoutGuide *weeklyAverageLayoutGuide;
@property (nonatomic, retain) UIImageView *weeklyAverageLine;
@property (nonatomic, retain) NSLayoutConstraint *weeklyAverageTrailingConstraint;

+ (id)baselineImage;
+ (id)bedtimeFieldImage;
+ (id)dashedAverageLineImage;

- (void).cxx_destruct;
- (id)aggregateUsageItem;
- (id)barSectionLayoutGuide;
- (id)barViewHeightConstraints;
- (id)barViews;
- (id)bedtime;
- (id)bedtimeFieldLayoutGuide;
- (id)bedtimeFields;
- (id)createBarViewWithUsageItems:(id)arg1 layoutGuide:(id)arg2 previousView:(id)arg3 previousLayoutGuide:(id)arg4 layoutGuideWidthMultiplier:(double)arg5 startDate:(id)arg6;
- (id)createBedtimeField;
- (id)createDividerWithView:(id)arg1 layoutGuide:(id)arg2 previousLayoutGuide:(id)arg3 layoutGuideWidthMultiplier:(double)arg4;
- (id)createFirstDivider;
- (id)createWeeklyAverageLineWithLayoutGuide:(id)arg1;
- (bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (id)graphLayoutGuide;
- (void)handleGesture:(id)arg1;
- (unsigned long long)higherResolutionCalendarUnit;
- (id)horizontalBaseline;
- (id)initWithTitleView:(id)arg1 graphHeight:(double)arg2;
- (id)labelSectionLayoutGuide;
- (id)paddleConnectorView;
- (id)paddleView;
- (id)paddleViewCenterXConstraint;
- (id)paddleViewConnectorCenterXConstraint;
- (void)selectBarWithClosestHorizontalPositionToPoint:(struct CGPoint { double x1; double x2; })arg1;
- (id)selectedBarView;
- (void)setAggregateUsageItem:(id)arg1;
- (void)setBarSectionLayoutGuide:(id)arg1;
- (void)setBarViewHeightConstraints:(id)arg1;
- (void)setBarViews:(id)arg1;
- (void)setBedtime:(id)arg1;
- (void)setBedtimeFieldLayoutGuide:(id)arg1;
- (void)setBedtimeFields:(id)arg1;
- (void)setGraphLayoutGuide:(id)arg1;
- (void)setHigherResolutionCalendarUnit:(unsigned long long)arg1;
- (void)setHorizontalBaseline:(id)arg1;
- (void)setLabelSectionLayoutGuide:(id)arg1;
- (void)setPaddleConnectorView:(id)arg1;
- (void)setPaddleView:(id)arg1;
- (void)setPaddleViewCenterXConstraint:(id)arg1;
- (void)setPaddleViewConnectorCenterXConstraint:(id)arg1;
- (void)setSelectedBarView:(id)arg1;
- (void)setStartDate:(id)arg1;
- (void)setTimePeriod:(unsigned long long)arg1;
- (void)setTimePeriodUnit:(unsigned long long)arg1;
- (void)setUpBarViewHeightContraints;
- (void)setUpBedtimeFields;
- (void)setUpGraphWithDividerInterval:(unsigned long long)arg1 labelFormatter:(id)arg2;
- (void)setUpWeeklyAverageLine:(bool)arg1;
- (void)setUsageItems:(id)arg1;
- (void)setUsageItems:(id)arg1 aggregateUsageItem:(id)arg2 timePeriod:(unsigned long long)arg3 startDate:(id)arg4 timePeriodUnit:(unsigned long long)arg5 higherResolutionCalendarUnit:(unsigned long long)arg6 animated:(bool)arg7;
- (void)setVerticalDividers:(id)arg1;
- (void)setVerticalLayoutGuides:(id)arg1;
- (void)setWeeklyAverageHeightConstraint:(id)arg1;
- (void)setWeeklyAverageLayoutGuide:(id)arg1;
- (void)setWeeklyAverageLine:(id)arg1;
- (void)setWeeklyAverageTrailingConstraint:(id)arg1;
- (id)startDate;
- (unsigned long long)timePeriod;
- (unsigned long long)timePeriodUnit;
- (id)titleView;
- (void)updateBarViews;
- (id)usageItems;
- (id)verticalDividers;
- (id)verticalLayoutGuides;
- (id)weeklyAverageHeightConstraint;
- (id)weeklyAverageLayoutGuide;
- (id)weeklyAverageLine;
- (id)weeklyAverageTrailingConstraint;

@end
