/* made by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXCompleteMyMomentSettings : PXSettings <PXCMMWorkflowCoordinatorDelegate> {
    bool  _allowLayoutTransitionGesture;
    bool  _allowOneUpGesture;
    bool  _allowSwipeSelection;
    bool  _alwaysDownloadBubbles;
    bool  _alwaysSortAfterAddMore;
    bool  _autoAcceptBubbles;
    bool  _cmmFeatureEnabled;
    bool  _directSendMessages;
    bool  _enableLightCuration;
    bool  _fakeMomentShareURL;
    bool  _graphSuggestionEnabled;
    long long  _initialLayoutType;
    bool  _insertNewRecipientsAtTheEnd;
    long long  _invitationsDataSourceType;
    long long  _maxNumberOfRecentsPeopleSuggested;
    long long  _numberOfSelectedAssetsRequiredToShowPrompt;
    long long  _overrideNumberOfColumnsInLandscape;
    long long  _overrideNumberOfColumnsInPortrait;
    long long  _peopleSuggestionsDataSourceType;
    double  _peopleSuggestionsTimeout;
    long long  _publishTransport;
    long long  _recentsModelType;
    bool  _recentsSuggestionEnabled;
    double  _recentsSuggestionTimeout;
    long long  _reviewFlow;
    long long  _reviewFlowDataSourceType;
    bool  _sectionHeadersShouldFloat;
    long long  _sendBackDataSourceType;
    long long  _sharingLinkType;
    bool  _shouldShowInlineAddButton;
    bool  _shouldShowSharePrompt;
    bool  _showAttachedHeaderView;
    bool  _showCMMSettingsAtTopLevel;
    bool  _showDebugStatus;
    bool  _showFloatingBanner;
    bool  _showIncomingShares;
    bool  _showMergeCandidateSuggestionsAfterBootstrapNaming;
    bool  _showMessage;
    bool  _showMessageTextEntryGadget;
    bool  _showMomentShareMessages;
    bool  _showOtherTitle;
    bool  _showOutgoingShares;
    bool  _showPeopleSuggestions;
    bool  _showProgressInGrid;
    bool  _showSectionHeaders;
    bool  _showSendBackFooterView;
    bool  _showSenderField;
    bool  _showStatusFooterView;
    bool  _showSubtitle;
    bool  _showTitle;
    bool  _showURLInBubble;
    bool  _simulateDelays;
    long long  _suggestionsDataSourceType;
    unsigned long long  _suggestionsMatchingStrategy;
    long long  _suggestionsScrollDirection;
    bool  _useDebugColors;
    PXCMMWorkflowCoordinator * _workflowCoordinator;
}

@property (nonatomic) bool allowLayoutTransitionGesture;
@property (nonatomic) bool allowOneUpGesture;
@property (nonatomic) bool allowSwipeSelection;
@property (nonatomic) bool alwaysDownloadBubbles;
@property (nonatomic) bool alwaysSortAfterAddMore;
@property (nonatomic) bool autoAcceptBubbles;
@property (nonatomic) bool cmmFeatureEnabled;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic) bool directSendMessages;
@property (nonatomic) bool enableLightCuration;
@property (nonatomic) bool fakeMomentShareURL;
@property (nonatomic) bool graphSuggestionEnabled;
@property (readonly) unsigned long long hash;
@property (nonatomic) long long initialLayoutType;
@property (nonatomic) bool insertNewRecipientsAtTheEnd;
@property (nonatomic) long long invitationsDataSourceType;
@property (nonatomic) long long maxNumberOfRecentsPeopleSuggested;
@property (nonatomic) long long numberOfSelectedAssetsRequiredToShowPrompt;
@property (nonatomic) long long overrideNumberOfColumnsInLandscape;
@property (nonatomic) long long overrideNumberOfColumnsInPortrait;
@property (nonatomic) long long peopleSuggestionsDataSourceType;
@property (nonatomic) double peopleSuggestionsTimeout;
@property (nonatomic) long long publishTransport;
@property (nonatomic) long long recentsModelType;
@property (nonatomic) bool recentsSuggestionEnabled;
@property (nonatomic) double recentsSuggestionTimeout;
@property (nonatomic) long long reviewFlow;
@property (nonatomic) long long reviewFlowDataSourceType;
@property (nonatomic) bool sectionHeadersShouldFloat;
@property (nonatomic) long long sendBackDataSourceType;
@property (nonatomic) long long sharingLinkType;
@property (nonatomic) bool shouldShowInlineAddButton;
@property (nonatomic) bool shouldShowSharePrompt;
@property (nonatomic) bool showAttachedHeaderView;
@property (nonatomic) bool showCMMSettingsAtTopLevel;
@property (nonatomic) bool showDebugStatus;
@property (nonatomic) bool showFloatingBanner;
@property (nonatomic) bool showIncomingShares;
@property (nonatomic) bool showMergeCandidateSuggestionsAfterBootstrapNaming;
@property (nonatomic) bool showMessage;
@property (nonatomic) bool showMessageTextEntryGadget;
@property (nonatomic) bool showMomentShareMessages;
@property (nonatomic) bool showOtherTitle;
@property (nonatomic) bool showOutgoingShares;
@property (nonatomic) bool showPeopleSuggestions;
@property (nonatomic) bool showProgressInGrid;
@property (nonatomic) bool showSectionHeaders;
@property (nonatomic) bool showSendBackFooterView;
@property (nonatomic) bool showSenderField;
@property (nonatomic) bool showStatusFooterView;
@property (nonatomic) bool showSubtitle;
@property (nonatomic) bool showTitle;
@property (nonatomic) bool showURLInBubble;
@property (nonatomic) bool simulateDelays;
@property (nonatomic) long long suggestionsDataSourceType;
@property (nonatomic) unsigned long long suggestionsMatchingStrategy;
@property (nonatomic) long long suggestionsScrollDirection;
@property (readonly) Class superclass;
@property (nonatomic) bool useDebugColors;
@property (nonatomic, readonly) PXCMMWorkflowCoordinator *workflowCoordinator;

+ (id)settingsControllerModule;
+ (id)sharedInstance;
+ (id)transientProperties;

- (void).cxx_destruct;
- (bool)allowLayoutTransitionGesture;
- (bool)allowOneUpGesture;
- (bool)allowSwipeSelection;
- (bool)alwaysDownloadBubbles;
- (bool)alwaysSortAfterAddMore;
- (bool)autoAcceptBubbles;
- (bool)cmmFeatureEnabled;
- (bool)directSendMessages;
- (bool)enableLightCuration;
- (bool)fakeMomentShareURL;
- (bool)graphSuggestionEnabled;
- (long long)initialLayoutType;
- (bool)insertNewRecipientsAtTheEnd;
- (long long)invitationsDataSourceType;
- (long long)maxNumberOfRecentsPeopleSuggested;
- (long long)numberOfSelectedAssetsRequiredToShowPrompt;
- (long long)overrideNumberOfColumnsInLandscape;
- (long long)overrideNumberOfColumnsInPortrait;
- (id)parentSettings;
- (long long)peopleSuggestionsDataSourceType;
- (double)peopleSuggestionsTimeout;
- (long long)publishTransport;
- (long long)recentsModelType;
- (bool)recentsSuggestionEnabled;
- (double)recentsSuggestionTimeout;
- (long long)reviewFlow;
- (long long)reviewFlowDataSourceType;
- (bool)sectionHeadersShouldFloat;
- (long long)sendBackDataSourceType;
- (void)setAllowLayoutTransitionGesture:(bool)arg1;
- (void)setAllowOneUpGesture:(bool)arg1;
- (void)setAllowSwipeSelection:(bool)arg1;
- (void)setAlwaysDownloadBubbles:(bool)arg1;
- (void)setAlwaysSortAfterAddMore:(bool)arg1;
- (void)setAutoAcceptBubbles:(bool)arg1;
- (void)setCmmFeatureEnabled:(bool)arg1;
- (void)setDefaultValues;
- (void)setDirectSendMessages:(bool)arg1;
- (void)setEnableLightCuration:(bool)arg1;
- (void)setFakeMomentShareURL:(bool)arg1;
- (void)setGraphSuggestionEnabled:(bool)arg1;
- (void)setInitialLayoutType:(long long)arg1;
- (void)setInsertNewRecipientsAtTheEnd:(bool)arg1;
- (void)setInvitationsDataSourceType:(long long)arg1;
- (void)setMaxNumberOfRecentsPeopleSuggested:(long long)arg1;
- (void)setNumberOfSelectedAssetsRequiredToShowPrompt:(long long)arg1;
- (void)setOverrideNumberOfColumnsInLandscape:(long long)arg1;
- (void)setOverrideNumberOfColumnsInPortrait:(long long)arg1;
- (void)setPeopleSuggestionsDataSourceType:(long long)arg1;
- (void)setPeopleSuggestionsTimeout:(double)arg1;
- (void)setPublishTransport:(long long)arg1;
- (void)setRecentsModelType:(long long)arg1;
- (void)setRecentsSuggestionEnabled:(bool)arg1;
- (void)setRecentsSuggestionTimeout:(double)arg1;
- (void)setReviewFlow:(long long)arg1;
- (void)setReviewFlowDataSourceType:(long long)arg1;
- (void)setSectionHeadersShouldFloat:(bool)arg1;
- (void)setSendBackDataSourceType:(long long)arg1;
- (void)setSharingLinkType:(long long)arg1;
- (void)setShouldShowInlineAddButton:(bool)arg1;
- (void)setShouldShowSharePrompt:(bool)arg1;
- (void)setShowAttachedHeaderView:(bool)arg1;
- (void)setShowCMMSettingsAtTopLevel:(bool)arg1;
- (void)setShowDebugStatus:(bool)arg1;
- (void)setShowFloatingBanner:(bool)arg1;
- (void)setShowIncomingShares:(bool)arg1;
- (void)setShowMergeCandidateSuggestionsAfterBootstrapNaming:(bool)arg1;
- (void)setShowMessage:(bool)arg1;
- (void)setShowMessageTextEntryGadget:(bool)arg1;
- (void)setShowMomentShareMessages:(bool)arg1;
- (void)setShowOtherTitle:(bool)arg1;
- (void)setShowOutgoingShares:(bool)arg1;
- (void)setShowPeopleSuggestions:(bool)arg1;
- (void)setShowProgressInGrid:(bool)arg1;
- (void)setShowSectionHeaders:(bool)arg1;
- (void)setShowSendBackFooterView:(bool)arg1;
- (void)setShowSenderField:(bool)arg1;
- (void)setShowStatusFooterView:(bool)arg1;
- (void)setShowSubtitle:(bool)arg1;
- (void)setShowTitle:(bool)arg1;
- (void)setShowURLInBubble:(bool)arg1;
- (void)setSimulateDelays:(bool)arg1;
- (void)setSuggestionsDataSourceType:(long long)arg1;
- (void)setSuggestionsMatchingStrategy:(unsigned long long)arg1;
- (void)setSuggestionsScrollDirection:(long long)arg1;
- (void)setUseDebugColors:(bool)arg1;
- (long long)sharingLinkType;
- (bool)shouldShowInlineAddButton;
- (bool)shouldShowSharePrompt;
- (bool)showAttachedHeaderView;
- (bool)showCMMSettingsAtTopLevel;
- (bool)showDebugStatus;
- (bool)showFloatingBanner;
- (bool)showIncomingShares;
- (bool)showMergeCandidateSuggestionsAfterBootstrapNaming;
- (bool)showMessage;
- (bool)showMessageTextEntryGadget;
- (bool)showMomentShareMessages;
- (bool)showOtherTitle;
- (bool)showOutgoingShares;
- (bool)showPeopleSuggestions;
- (bool)showProgressInGrid;
- (bool)showSectionHeaders;
- (bool)showSendBackFooterView;
- (bool)showSenderField;
- (bool)showStatusFooterView;
- (bool)showSubtitle;
- (bool)showTitle;
- (bool)showURLInBubble;
- (bool)simulateDelays;
- (long long)suggestionsDataSourceType;
- (unsigned long long)suggestionsMatchingStrategy;
- (long long)suggestionsScrollDirection;
- (bool)useDebugColors;
- (id)workflowCoordinator;
- (void)workflowCoordinator:(id)arg1 workflowViewController:(id)arg2 didFinishWithActivityState:(unsigned long long)arg3;

@end
