/* made by EzioChiu
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXGadgetViewController : UICollectionViewController <PXChangeObserver, PXGadgetCollectionViewLayoutDelegate, PXGadgetDelegate, PXNavigableGadgetViewController, PXSectionedDataSourceManagerObserver, UICollectionViewDelegateFlowLayout, UICollectionViewDropDelegate, UIViewControllerPreviewingDelegate> {
    <PXGadget> * _anchorGadget;
    UIColor * _backgroundColor;
    PXGadgetSpec * _currentGadgetSpec;
    bool  _currentlyVisible;
    PXGadgetDataSource * _dataSource;
    PXGadgetDataSourceManager * _dataSourceManager;
    bool  _gadgetAnimating;
    NSTimer * _gadgetSeenTimer;
    id /* block */  _gadgetsLoadedCompletionHandler;
    NSObject<OS_dispatch_group> * _gadgetsLoadingGroup;
    bool  _isContentVisible;
    PXGadgetLayoutSpec * _layoutSpec;
    NSMutableArray * _loadedGadgets;
    bool  _loadingGadgets;
    NSTimer * _navigationInvalidationTimer;
    unsigned long long  _numberOfInitialGadgetsToLoad;
    PXGadgetNavigationItem * _pendingNavigationItem;
    PXGadgetOrbContext * _previewOrbContext;
    <UIViewControllerPreviewing> * _previewingContext;
    NSMutableSet * _seenGadgetIdentifiers;
    <PXGadget> * _selectedGadget;
    struct PXGadgetUpdateFlags { 
        bool collectionNeedsUpdate; 
        bool currentGadgetSpecNeedsUpdate; 
        bool gadgetLoadingNeedsUpdate; 
    }  _updateFlags;
    NSMutableSet * _visibleGadgetsWantingVisibleRect;
}

@property (nonatomic) <PXGadget> *anchorGadget;
@property (nonatomic, copy) UIColor *backgroundColor;
@property (nonatomic, retain) PXGadgetSpec *currentGadgetSpec;
@property (getter=isCurrentlyVisible, nonatomic) bool currentlyVisible;
@property (nonatomic, retain) PXGadgetDataSource *dataSource;
@property (nonatomic, readonly) PXGadgetDataSourceManager *dataSourceManager;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (getter=isGadgetAnimating, nonatomic) bool gadgetAnimating;
@property (nonatomic, retain) NSTimer *gadgetSeenTimer;
@property (nonatomic, readonly) NSObject<OS_os_log> *gadgetViewControllerLog;
@property (nonatomic, copy) id /* block */ gadgetsLoadedCompletionHandler;
@property (nonatomic, retain) NSObject<OS_dispatch_group> *gadgetsLoadingGroup;
@property (readonly) unsigned long long hash;
@property (setter=setContentVisible:, nonatomic) bool isContentVisible;
@property (nonatomic, readonly) PXGadgetCollectionViewLayout *layout;
@property (nonatomic, retain) PXGadgetLayoutSpec *layoutSpec;
@property (nonatomic, retain) NSMutableArray *loadedGadgets;
@property (getter=isLoadingGadgets, nonatomic) bool loadingGadgets;
@property (nonatomic, retain) NSTimer *navigationInvalidationTimer;
@property (nonatomic) <PXGadgetDelegate> *nextGadgetResponder;
@property (nonatomic) unsigned long long numberOfInitialGadgetsToLoad;
@property (nonatomic, retain) PXGadgetNavigationItem *pendingNavigationItem;
@property (nonatomic, retain) PXGadgetOrbContext *previewOrbContext;
@property (nonatomic, retain) <UIViewControllerPreviewing> *previewingContext;
@property (nonatomic, retain) NSMutableSet *seenGadgetIdentifiers;
@property (nonatomic, retain) <PXGadget> *selectedGadget;
@property (readonly) Class superclass;
@property (nonatomic) struct PXGadgetUpdateFlags { bool x1; bool x2; bool x3; } updateFlags;
@property (nonatomic, readonly) struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; } visibleBounds;
@property (nonatomic, retain) NSMutableSet *visibleGadgetsWantingVisibleRect;

// Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore

+ (Class)gadgetSpecClass;
+ (Class)layoutSpecClass;

- (void).cxx_destruct;
- (void)_configureHeader:(id)arg1 withGadget:(id)arg2;
- (void)_dataSourceManagerDidChange;
- (id)_gadgetAtIndexPath:(id)arg1;
- (id)_generateGadgetAnchor;
- (void)_handleGadgetsLoadingDelay;
- (void)_handleGadgetsSeen;
- (void)_informGadgetsLoadedIfNecessary;
- (void)_initializeDataSource;
- (void)_invalidatePendingNavigation;
- (void)_loadAllGadgetsIfNeededAndInvalidateLayout:(bool)arg1;
- (void)_loadGadgets:(id)arg1;
- (void)_navigateIfNeeded;
- (bool)_navigateToGadget:(id)arg1 animated:(bool)arg2 navigationBlock:(id /* block */)arg3;
- (void)_notifyGadgetsThatGadgetControllerHasAppeared;
- (void)_notifyPresentedGadgetsOfVisibilityChange;
- (void)_registerForPreview;
- (void)_scrollViewDidEndScrolling;
- (void)_unloadAllGadgets;
- (void)_unregisterForPreview;
- (void)_updateAllGadgetsSpecIfNeededAndInvalidateLayout:(bool)arg1;
- (void)_updateGadgetVisibleRects;
- (void)_updateHeaderForGadget:(id)arg1 atIndexPath:(id)arg2;
- (void)_updateNavigationBarPrefersLargeTitles:(bool)arg1;
- (void)_updateVisibleGadgetHeaders;
- (id)anchorGadget;
- (long long)anchorPosition;
- (id)backgroundColor;
- (bool)collectionView:(id)arg1 canHandleDropSesson:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didEndDisplayingCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 dropSessionDidUpdate:(id)arg2 withDestinationIndexPath:(id)arg3;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (struct CGSize { double x1; double x2; })collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(long long)arg3;
- (struct CGSize { double x1; double x2; })collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)collectionView:(id)arg1 performDropWithCoordinator:(id)arg2;
- (bool)collectionView:(id)arg1 shouldHighlightItemAtIndexPath:(id)arg2;
- (bool)collectionView:(id)arg1 shouldSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 willDisplayCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (void)contentSizeCategoryDidChangeNotification:(id)arg1;
- (id)currentGadgetSpec;
- (id)dataSource;
- (id)dataSourceManager;
- (void)dealloc;
- (void)didDismissPreviewViewController:(id)arg1 committing:(bool)arg2;
- (void)didReceiveMemoryWarning;
- (void)extendedTraitCollectionDidChange:(unsigned long long)arg1;
- (void)gadget:(id)arg1 animateChanges:(id /* block */)arg2;
- (void)gadget:(id)arg1 didChange:(unsigned long long)arg2;
- (bool)gadget:(id)arg1 transitionToViewController:(struct NSObject { Class x1; }*)arg2 animated:(bool)arg3;
- (id)gadgetAtLocation:(struct CGPoint { double x1; double x2; })arg1 inCoordinateSpace:(id)arg2;
- (void)gadgetControllerFinishedUpdatingDataSource;
- (id)gadgetSeenTimer;
- (struct NSObject { Class x1; }*)gadgetViewControllerHostingGadget:(id)arg1;
- (id)gadgetViewControllerLog;
- (id /* block */)gadgetsLoadedCompletionHandler;
- (id)gadgetsLoadingGroup;
- (id)gridPresentation;
- (id)indexPathForGadget:(id)arg1;
- (id)initWithLayout:(id)arg1 dataSourceManager:(id)arg2;
- (bool)isContentVisible;
- (bool)isCurrentlyVisible;
- (bool)isGadgetAnimating;
- (bool)isLoadingGadgets;
- (bool)isRootGadgetViewController;
- (id)layout;
- (id)layoutSpec;
- (void)loadAllGadgets;
- (id)loadedGadgets;
- (bool)navigateToFirstGadgetWithType:(unsigned long long)arg1 animated:(bool)arg2;
- (bool)navigateToFirstGadgetWithTypeDeferIfNeeded:(unsigned long long)arg1 animated:(bool)arg2 nestedNavigationBlock:(id /* block */)arg3;
- (bool)navigateToGadget:(id)arg1 animated:(bool)arg2;
- (bool)navigateToGadgetWithIdDeferIfNeeded:(id)arg1 animated:(bool)arg2 nestingNavigationBlock:(id /* block */)arg3;
- (id)navigationInvalidationTimer;
- (id)nextGadgetResponder;
- (unsigned long long)numberOfInitialGadgetsToLoad;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)observable:(id)arg1 didChange:(unsigned long long)arg2 context:(void*)arg3;
- (id)oneUpPresentation;
- (id)pendingNavigationItem;
- (void)performBlockAfterGadgetsLoadingCompletes:(id /* block */)arg1;
- (void)ppt_performBlockAfterAllGadgetsLoadingCompletes:(id /* block */)arg1;
- (id)previewOrbContext;
- (id)previewingContext;
- (void)previewingContext:(id)arg1 commitViewController:(id)arg2;
- (id)previewingContext:(id)arg1 viewControllerForLocation:(struct CGPoint { double x1; double x2; })arg2;
- (bool)pu_handleSecondTabTap;
- (bool)px_canPerformZoomTransitionWithDetailViewController:(id)arg1;
- (id)px_diagnosticsItemProvidersForPoint:(struct CGPoint { double x1; double x2; })arg1 inCoordinateSpace:(id)arg2;
- (id)px_endPointForTransition:(id)arg1;
- (void)reloadContent;
- (bool)scrollGadgetToVisible:(id)arg1 animated:(bool)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(bool)arg2;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (id)seenGadgetIdentifiers;
- (id)selectedGadget;
- (void)setAnchorGadget:(id)arg1;
- (void)setBackgroundColor:(id)arg1;
- (void)setContentVisible:(bool)arg1;
- (void)setCurrentGadgetSpec:(id)arg1;
- (void)setCurrentlyVisible:(bool)arg1;
- (void)setDataSource:(id)arg1;
- (void)setGadgetAnimating:(bool)arg1;
- (void)setGadgetSeenTimer:(id)arg1;
- (void)setGadgetsLoadedCompletionHandler:(id /* block */)arg1;
- (void)setGadgetsLoadingGroup:(id)arg1;
- (void)setLayoutSpec:(id)arg1;
- (void)setLoadedGadgets:(id)arg1;
- (void)setLoadingGadgets:(bool)arg1;
- (void)setNavigationInvalidationTimer:(id)arg1;
- (void)setNumberOfInitialGadgetsToLoad:(unsigned long long)arg1;
- (void)setPendingNavigationItem:(id)arg1;
- (void)setPreviewOrbContext:(id)arg1;
- (void)setPreviewingContext:(id)arg1;
- (void)setSeenGadgetIdentifiers:(id)arg1;
- (void)setSelectedGadget:(id)arg1;
- (void)setUpdateFlags:(struct PXGadgetUpdateFlags { bool x1; bool x2; bool x3; })arg1;
- (void)setVisibleGadgetsWantingVisibleRect:(id)arg1;
- (void)traitCollectionDidChange:(id)arg1;
- (struct PXGadgetUpdateFlags { bool x1; bool x2; bool x3; })updateFlags;
- (void)updateIfNeeded;
- (void)viewDidAppear:(bool)arg1;
- (void)viewDidDisappear:(bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillAppear:(bool)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewWillTransitionToSize:(struct CGSize { double x1; double x2; })arg1 withTransitionCoordinator:(id)arg2;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })visibleBounds;
- (void)visibleBoundsDidChange;
- (id)visibleGadgetsWantingVisibleRect;

// Image: /System/Library/Frameworks/PhotosUI.framework/PhotosUI

- (id)px_gridPresentation;

@end
