/* made by EzioChiu
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UIStatusBarServerThread : NSThread {
    NSMutableArray * _clientPorts;
    struct { 
        bool itemIsEnabled[36]; 
        BOOL timeString[64]; 
        BOOL shortTimeString[64]; 
        BOOL dateString[256]; 
        int gsmSignalStrengthRaw; 
        int gsmSignalStrengthBars; 
        BOOL serviceString[100]; 
        BOOL serviceCrossfadeString[100]; 
        BOOL serviceImages[2][100]; 
        BOOL operatorDirectory[1024]; 
        unsigned int serviceContentType; 
        int wifiSignalStrengthRaw; 
        int wifiSignalStrengthBars; 
        unsigned int dataNetworkType; 
        int batteryCapacity; 
        unsigned int batteryState; 
        BOOL batteryDetailString[150]; 
        int bluetoothBatteryCapacity; 
        int thermalColor; 
        unsigned int thermalSunlightMode : 1; 
        unsigned int slowActivity : 1; 
        unsigned int syncActivity : 1; 
        BOOL activityDisplayId[256]; 
        unsigned int bluetoothConnected : 1; 
        unsigned int displayRawGSMSignal : 1; 
        unsigned int displayRawWifiSignal : 1; 
        unsigned int locationIconType : 1; 
        unsigned int quietModeInactive : 1; 
        unsigned int tetheringConnectionCount; 
        unsigned int batterySaverModeActive : 1; 
        unsigned int deviceIsRTL : 1; 
        unsigned int lock : 1; 
        BOOL breadcrumbTitle[256]; 
        BOOL breadcrumbSecondaryTitle[256]; 
        BOOL personName[100]; 
        unsigned int electronicTollCollectionAvailable : 1; 
        unsigned int wifiLinkWarning : 1; 
        unsigned int wifiSearching : 1; 
        double backgroundActivityDisplayStartDate; 
        unsigned int shouldShowEmergencyOnlyStatus : 1; 
    }  _composedStatusBarData;
    bool  _composedStatusBarDataValid;
    struct __CFDictionary { } * _doubleHeightStatusStrings;
    NSMutableDictionary * _glowAnimationEndTimes;
    struct __CFDictionary { } * _glowAnimationStates;
    _UIStatusBarTimeStringServerCache * _ioSurfaceCache;
    struct { 
        bool overrideItemIsEnabled[36]; 
        unsigned int overrideTimeString : 1; 
        unsigned int overrideDateString : 1; 
        unsigned int overrideGsmSignalStrengthRaw : 1; 
        unsigned int overrideGsmSignalStrengthBars : 1; 
        unsigned int overrideServiceString : 1; 
        unsigned int overrideServiceImages : 2; 
        unsigned int overrideOperatorDirectory : 1; 
        unsigned int overrideServiceContentType : 1; 
        unsigned int overrideWifiSignalStrengthRaw : 1; 
        unsigned int overrideWifiSignalStrengthBars : 1; 
        unsigned int overrideDataNetworkType : 1; 
        unsigned int disallowsCellularDataNetworkTypes : 1; 
        unsigned int overrideBatteryCapacity : 1; 
        unsigned int overrideBatteryState : 1; 
        unsigned int overrideBatteryDetailString : 1; 
        unsigned int overrideBluetoothBatteryCapacity : 1; 
        unsigned int overrideThermalColor : 1; 
        unsigned int overrideSlowActivity : 1; 
        unsigned int overrideActivityDisplayId : 1; 
        unsigned int overrideBluetoothConnected : 1; 
        unsigned int overrideBreadcrumb : 1; 
        unsigned int overrideLock; 
        unsigned int overrideDisplayRawGSMSignal : 1; 
        unsigned int overrideDisplayRawWifiSignal : 1; 
        unsigned int overridePersonName : 1; 
        unsigned int overrideWifiLinkWarning : 1; 
        struct { 
            bool itemIsEnabled[36]; 
            BOOL timeString[64]; 
            BOOL shortTimeString[64]; 
            BOOL dateString[256]; 
            int gsmSignalStrengthRaw; 
            int gsmSignalStrengthBars; 
            BOOL serviceString[100]; 
            BOOL serviceCrossfadeString[100]; 
            BOOL serviceImages[2][100]; 
            BOOL operatorDirectory[1024]; 
            unsigned int serviceContentType; 
            int wifiSignalStrengthRaw; 
            int wifiSignalStrengthBars; 
            unsigned int dataNetworkType; 
            int batteryCapacity; 
            unsigned int batteryState; 
            BOOL batteryDetailString[150]; 
            int bluetoothBatteryCapacity; 
            int thermalColor; 
            unsigned int thermalSunlightMode : 1; 
            unsigned int slowActivity : 1; 
            unsigned int syncActivity : 1; 
            BOOL activityDisplayId[256]; 
            unsigned int bluetoothConnected : 1; 
            unsigned int displayRawGSMSignal : 1; 
            unsigned int displayRawWifiSignal : 1; 
            unsigned int locationIconType : 1; 
            unsigned int quietModeInactive : 1; 
            unsigned int tetheringConnectionCount; 
            unsigned int batterySaverModeActive : 1; 
            unsigned int deviceIsRTL : 1; 
            unsigned int lock : 1; 
            BOOL breadcrumbTitle[256]; 
            BOOL breadcrumbSecondaryTitle[256]; 
            BOOL personName[100]; 
            unsigned int electronicTollCollectionAvailable : 1; 
            unsigned int wifiLinkWarning : 1; 
            unsigned int wifiSearching : 1; 
            double backgroundActivityDisplayStartDate; 
            unsigned int shouldShowEmergencyOnlyStatus : 1; 
        } values; 
    }  _overrides;
    NSMutableArray * _publishers;
    struct { 
        bool itemIsEnabled[36]; 
        BOOL timeString[64]; 
        BOOL shortTimeString[64]; 
        BOOL dateString[256]; 
        int gsmSignalStrengthRaw; 
        int gsmSignalStrengthBars; 
        BOOL serviceString[100]; 
        BOOL serviceCrossfadeString[100]; 
        BOOL serviceImages[2][100]; 
        BOOL operatorDirectory[1024]; 
        unsigned int serviceContentType; 
        int wifiSignalStrengthRaw; 
        int wifiSignalStrengthBars; 
        unsigned int dataNetworkType; 
        int batteryCapacity; 
        unsigned int batteryState; 
        BOOL batteryDetailString[150]; 
        int bluetoothBatteryCapacity; 
        int thermalColor; 
        unsigned int thermalSunlightMode : 1; 
        unsigned int slowActivity : 1; 
        unsigned int syncActivity : 1; 
        BOOL activityDisplayId[256]; 
        unsigned int bluetoothConnected : 1; 
        unsigned int displayRawGSMSignal : 1; 
        unsigned int displayRawWifiSignal : 1; 
        unsigned int locationIconType : 1; 
        unsigned int quietModeInactive : 1; 
        unsigned int tetheringConnectionCount; 
        unsigned int batterySaverModeActive : 1; 
        unsigned int deviceIsRTL : 1; 
        unsigned int lock : 1; 
        BOOL breadcrumbTitle[256]; 
        BOOL breadcrumbSecondaryTitle[256]; 
        BOOL personName[100]; 
        unsigned int electronicTollCollectionAvailable : 1; 
        unsigned int wifiLinkWarning : 1; 
        unsigned int wifiSearching : 1; 
        double backgroundActivityDisplayStartDate; 
        unsigned int shouldShowEmergencyOnlyStatus : 1; 
    }  _statusBarData;
}

@property (nonatomic, readonly) _UIStatusBarTimeStringServerCache *ioSurfaceCache;

- (void).cxx_destruct;
- (void)_addClient:(unsigned int)arg1;
- (void)_addStatusBarItem:(int)arg1 forPublisher:(id)arg2;
- (void)_addStyleOverrides:(int)arg1 forPublisher:(id)arg2;
- (void)_broadcastStatusBarDataWithActions:(int)arg1 animated:(bool)arg2;
- (void)_broadcastStyleOverrides;
- (id)_doubleHeightStatusStringForStyle:(long long)arg1;
- (double)_glowAnimationEndTimeForStyle:(long long)arg1;
- (bool)_glowAnimationStateForStyle:(long long)arg1;
- (bool)_permanentizeStatusBarOverrideData;
- (void)_postDoubleHeightStatus:(char *)arg1 forStyle:(long long)arg2;
- (void)_postGlowAnimationState:(bool)arg1 forStyle:(long long)arg2;
- (void)_postStatusBarData:(struct { bool x1[36]; BOOL x2[64]; BOOL x3[64]; BOOL x4[256]; int x5; int x6; BOOL x7[100]; BOOL x8[100]; BOOL x9[2][100]; BOOL x10[1024]; unsigned int x11; int x12; int x13; unsigned int x14; int x15; unsigned int x16; BOOL x17[150]; int x18; int x19; unsigned int x20 : 1; unsigned int x21 : 1; unsigned int x22 : 1; BOOL x23[256]; unsigned int x24 : 1; unsigned int x25 : 1; unsigned int x26 : 1; unsigned int x27 : 1; unsigned int x28 : 1; unsigned int x29; unsigned int x30 : 1; unsigned int x31 : 1; unsigned int x32 : 1; BOOL x33[256]; BOOL x34[256]; BOOL x35[100]; unsigned int x36 : 1; unsigned int x37 : 1; unsigned int x38 : 1; double x39; unsigned int x40 : 1; }*)arg1 actions:(int)arg2 animated:(bool)arg3;
- (void)_postStatusBarOverrideData:(struct { bool x1[36]; unsigned int x2 : 1; unsigned int x3 : 1; unsigned int x4 : 1; unsigned int x5 : 1; unsigned int x6 : 1; unsigned int x7 : 2; unsigned int x8 : 1; unsigned int x9 : 1; unsigned int x10 : 1; unsigned int x11 : 1; unsigned int x12 : 1; unsigned int x13 : 1; unsigned int x14 : 1; unsigned int x15 : 1; unsigned int x16 : 1; unsigned int x17 : 1; unsigned int x18 : 1; unsigned int x19 : 1; unsigned int x20 : 1; unsigned int x21 : 1; unsigned int x22 : 1; unsigned int x23; unsigned int x24 : 1; unsigned int x25 : 1; unsigned int x26 : 1; unsigned int x27 : 1; struct { bool x_28_1_1[36]; BOOL x_28_1_2[64]; BOOL x_28_1_3[64]; BOOL x_28_1_4[256]; int x_28_1_5; int x_28_1_6; BOOL x_28_1_7[100]; BOOL x_28_1_8[100]; BOOL x_28_1_9[2][100]; BOOL x_28_1_10[1024]; unsigned int x_28_1_11; int x_28_1_12; int x_28_1_13; unsigned int x_28_1_14; int x_28_1_15; unsigned int x_28_1_16; BOOL x_28_1_17[150]; int x_28_1_18; int x_28_1_19; unsigned int x_28_1_20 : 1; unsigned int x_28_1_21 : 1; unsigned int x_28_1_22 : 1; BOOL x_28_1_23[256]; unsigned int x_28_1_24 : 1; unsigned int x_28_1_25 : 1; unsigned int x_28_1_26 : 1; unsigned int x_28_1_27 : 1; unsigned int x_28_1_28 : 1; unsigned int x_28_1_29; unsigned int x_28_1_30 : 1; unsigned int x_28_1_31 : 1; unsigned int x_28_1_32 : 1; BOOL x_28_1_33[256]; BOOL x_28_1_34[256]; BOOL x_28_1_35[100]; unsigned int x_28_1_36 : 1; unsigned int x_28_1_37 : 1; unsigned int x_28_1_38 : 1; double x_28_1_39; unsigned int x_28_1_40 : 1; } x28; }*)arg1;
- (id)_publisherForPort:(unsigned int)arg1;
- (void)_removeAnimationEndTimesForOverrides:(int)arg1;
- (void)_removeClient:(struct __CFMachPort { }*)arg1;
- (void)_removePublisher:(struct __CFMachPort { }*)arg1;
- (void)_removeStatusBarItem:(int)arg1 forPublisher:(id)arg2;
- (void)_removeStyleOverrides:(int)arg1 forPublisher:(id)arg2;
- (void)_setAnimationEndTimesForOverrides:(int)arg1;
- (struct { bool x1[36]; BOOL x2[64]; BOOL x3[64]; BOOL x4[256]; int x5; int x6; BOOL x7[100]; BOOL x8[100]; BOOL x9[2][100]; BOOL x10[1024]; unsigned int x11; int x12; int x13; unsigned int x14; int x15; unsigned int x16; BOOL x17[150]; int x18; int x19; unsigned int x20 : 1; unsigned int x21 : 1; unsigned int x22 : 1; BOOL x23[256]; unsigned int x24 : 1; unsigned int x25 : 1; unsigned int x26 : 1; unsigned int x27 : 1; unsigned int x28 : 1; unsigned int x29; unsigned int x30 : 1; unsigned int x31 : 1; unsigned int x32 : 1; BOOL x33[256]; BOOL x34[256]; BOOL x35[100]; unsigned int x36 : 1; unsigned int x37 : 1; unsigned int x38 : 1; double x39; unsigned int x40 : 1; }*)_statusBarData;
- (struct { bool x1[36]; unsigned int x2 : 1; unsigned int x3 : 1; unsigned int x4 : 1; unsigned int x5 : 1; unsigned int x6 : 1; unsigned int x7 : 2; unsigned int x8 : 1; unsigned int x9 : 1; unsigned int x10 : 1; unsigned int x11 : 1; unsigned int x12 : 1; unsigned int x13 : 1; unsigned int x14 : 1; unsigned int x15 : 1; unsigned int x16 : 1; unsigned int x17 : 1; unsigned int x18 : 1; unsigned int x19 : 1; unsigned int x20 : 1; unsigned int x21 : 1; unsigned int x22 : 1; unsigned int x23; unsigned int x24 : 1; unsigned int x25 : 1; unsigned int x26 : 1; unsigned int x27 : 1; struct { bool x_28_1_1[36]; BOOL x_28_1_2[64]; BOOL x_28_1_3[64]; BOOL x_28_1_4[256]; int x_28_1_5; int x_28_1_6; BOOL x_28_1_7[100]; BOOL x_28_1_8[100]; BOOL x_28_1_9[2][100]; BOOL x_28_1_10[1024]; unsigned int x_28_1_11; int x_28_1_12; int x_28_1_13; unsigned int x_28_1_14; int x_28_1_15; unsigned int x_28_1_16; BOOL x_28_1_17[150]; int x_28_1_18; int x_28_1_19; unsigned int x_28_1_20 : 1; unsigned int x_28_1_21 : 1; unsigned int x_28_1_22 : 1; BOOL x_28_1_23[256]; unsigned int x_28_1_24 : 1; unsigned int x_28_1_25 : 1; unsigned int x_28_1_26 : 1; unsigned int x_28_1_27 : 1; unsigned int x_28_1_28 : 1; unsigned int x_28_1_29; unsigned int x_28_1_30 : 1; unsigned int x_28_1_31 : 1; unsigned int x_28_1_32 : 1; BOOL x_28_1_33[256]; BOOL x_28_1_34[256]; BOOL x_28_1_35[100]; unsigned int x_28_1_36 : 1; unsigned int x_28_1_37 : 1; unsigned int x_28_1_38 : 1; double x_28_1_39; unsigned int x_28_1_40 : 1; } x28; }*)_statusBarOverrideData;
- (int)_styleOverrides;
- (id)ioSurfaceCache;
- (void)main;

@end
