/* made by EzioChiu
   Image: /System/Library/PrivateFrameworks/NewsTransport.framework/NewsTransport
 */

@interface NTPBSpecialEventsConfig : PBCodable <NSCopying> {
    NSString * _actionTitle;
    NSString * _actionUrl;
    NTPBColorGradient * _backgroundGradient;
    NSString * _fontName;
    double  _fontSize;
    double  _fontSizeIpad;
    double  _fontTracking;
    double  _fontTrackingIpad;
    NSMutableArray * _groupFonts;
    struct { 
        unsigned int fontSize : 1; 
        unsigned int fontSizeIpad : 1; 
        unsigned int fontTracking : 1; 
        unsigned int fontTrackingIpad : 1; 
        unsigned int titleOffsetHeight : 1; 
        unsigned int titleOffsetHeightIpad : 1; 
        unsigned int titleOffsetY : 1; 
        unsigned int titleOffsetYIpad : 1; 
        unsigned int micaEnabled : 1; 
    }  _has;
    NSMutableArray * _items;
    NSString * _micaAnimationFileUrl;
    NSString * _micaAnimationFileUrlIpad;
    bool  _micaEnabled;
    NSString * _title;
    NTPBColor * _titleColor;
    double  _titleOffsetHeight;
    double  _titleOffsetHeightIpad;
    double  _titleOffsetY;
    double  _titleOffsetYIpad;
}

@property (nonatomic, retain) NSString *actionTitle;
@property (nonatomic, retain) NSString *actionUrl;
@property (nonatomic, retain) NTPBColorGradient *backgroundGradient;
@property (nonatomic, retain) NSString *fontName;
@property (nonatomic) double fontSize;
@property (nonatomic) double fontSizeIpad;
@property (nonatomic) double fontTracking;
@property (nonatomic) double fontTrackingIpad;
@property (nonatomic, retain) NSMutableArray *groupFonts;
@property (nonatomic, readonly) bool hasActionTitle;
@property (nonatomic, readonly) bool hasActionUrl;
@property (nonatomic, readonly) bool hasBackgroundGradient;
@property (nonatomic, readonly) bool hasFontName;
@property (nonatomic) bool hasFontSize;
@property (nonatomic) bool hasFontSizeIpad;
@property (nonatomic) bool hasFontTracking;
@property (nonatomic) bool hasFontTrackingIpad;
@property (nonatomic, readonly) bool hasMicaAnimationFileUrl;
@property (nonatomic, readonly) bool hasMicaAnimationFileUrlIpad;
@property (nonatomic) bool hasMicaEnabled;
@property (nonatomic, readonly) bool hasTitle;
@property (nonatomic, readonly) bool hasTitleColor;
@property (nonatomic) bool hasTitleOffsetHeight;
@property (nonatomic) bool hasTitleOffsetHeightIpad;
@property (nonatomic) bool hasTitleOffsetY;
@property (nonatomic) bool hasTitleOffsetYIpad;
@property (nonatomic, retain) NSMutableArray *items;
@property (nonatomic, retain) NSString *micaAnimationFileUrl;
@property (nonatomic, retain) NSString *micaAnimationFileUrlIpad;
@property (nonatomic) bool micaEnabled;
@property (nonatomic, retain) NSString *title;
@property (nonatomic, retain) NTPBColor *titleColor;
@property (nonatomic) double titleOffsetHeight;
@property (nonatomic) double titleOffsetHeightIpad;
@property (nonatomic) double titleOffsetY;
@property (nonatomic) double titleOffsetYIpad;

+ (Class)groupFontsType;
+ (Class)itemsType;

- (id)actionTitle;
- (id)actionUrl;
- (void)addGroupFonts:(id)arg1;
- (void)addItems:(id)arg1;
- (id)backgroundGradient;
- (void)clearGroupFonts;
- (void)clearItems;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (id)description;
- (id)dictionaryRepresentation;
- (id)fontName;
- (double)fontSize;
- (double)fontSizeIpad;
- (double)fontTracking;
- (double)fontTrackingIpad;
- (id)groupFonts;
- (id)groupFontsAtIndex:(unsigned long long)arg1;
- (unsigned long long)groupFontsCount;
- (bool)hasActionTitle;
- (bool)hasActionUrl;
- (bool)hasBackgroundGradient;
- (bool)hasFontName;
- (bool)hasFontSize;
- (bool)hasFontSizeIpad;
- (bool)hasFontTracking;
- (bool)hasFontTrackingIpad;
- (bool)hasMicaAnimationFileUrl;
- (bool)hasMicaAnimationFileUrlIpad;
- (bool)hasMicaEnabled;
- (bool)hasTitle;
- (bool)hasTitleColor;
- (bool)hasTitleOffsetHeight;
- (bool)hasTitleOffsetHeightIpad;
- (bool)hasTitleOffsetY;
- (bool)hasTitleOffsetYIpad;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (id)items;
- (id)itemsAtIndex:(unsigned long long)arg1;
- (unsigned long long)itemsCount;
- (void)mergeFrom:(id)arg1;
- (id)micaAnimationFileUrl;
- (id)micaAnimationFileUrlIpad;
- (bool)micaEnabled;
- (bool)readFrom:(id)arg1;
- (void)setActionTitle:(id)arg1;
- (void)setActionUrl:(id)arg1;
- (void)setBackgroundGradient:(id)arg1;
- (void)setFontName:(id)arg1;
- (void)setFontSize:(double)arg1;
- (void)setFontSizeIpad:(double)arg1;
- (void)setFontTracking:(double)arg1;
- (void)setFontTrackingIpad:(double)arg1;
- (void)setGroupFonts:(id)arg1;
- (void)setHasFontSize:(bool)arg1;
- (void)setHasFontSizeIpad:(bool)arg1;
- (void)setHasFontTracking:(bool)arg1;
- (void)setHasFontTrackingIpad:(bool)arg1;
- (void)setHasMicaEnabled:(bool)arg1;
- (void)setHasTitleOffsetHeight:(bool)arg1;
- (void)setHasTitleOffsetHeightIpad:(bool)arg1;
- (void)setHasTitleOffsetY:(bool)arg1;
- (void)setHasTitleOffsetYIpad:(bool)arg1;
- (void)setItems:(id)arg1;
- (void)setMicaAnimationFileUrl:(id)arg1;
- (void)setMicaAnimationFileUrlIpad:(id)arg1;
- (void)setMicaEnabled:(bool)arg1;
- (void)setTitle:(id)arg1;
- (void)setTitleColor:(id)arg1;
- (void)setTitleOffsetHeight:(double)arg1;
- (void)setTitleOffsetHeightIpad:(double)arg1;
- (void)setTitleOffsetY:(double)arg1;
- (void)setTitleOffsetYIpad:(double)arg1;
- (id)title;
- (id)titleColor;
- (double)titleOffsetHeight;
- (double)titleOffsetHeightIpad;
- (double)titleOffsetY;
- (double)titleOffsetYIpad;
- (void)writeTo:(id)arg1;

@end
