/* made by EzioChiu
   Image: /System/Library/PrivateFrameworks/HealthDaemon.framework/HealthDaemon
 */

@interface HDWorkoutBuilderServer : HDStandardTaskServer <HDTaskServerObserver, HDWorkoutDataAccumulator, HDWorkoutDataDestination, HKDataFlowLinkProcessor, HKWorkoutBuilderServerInterface> {
    HKWorkoutBuilderConfiguration * _configuration;
    HKObserverSet * _dataAccumulatorObservers;
    NSDateInterval * _dataInterval;
    _HKDelayedOperation * _delayedPersistenceOperation;
    NSError * _error;
    NSSet * _expectedDataSourceUUIDs;
    NSMutableDictionary * _metadata;
    HDWorkoutBuilderEntity * _persistentEntity;
    NSSet * _quantityTypesIncludedWhilePaused;
    NSMutableSet * _quantityTypesRequiringCalculatorInvalidation;
    NSObject<OS_dispatch_queue> * _queue;
    HKObserverSet * _sampleObservers;
    NSMutableDictionary * _sourceOrderProvidersByType;
    unsigned long long  _state;
    NSMutableDictionary * _statisticsCalculatorsByType;
    NSMutableDictionary * _statisticsDataSourcesByType;
    HKDataFlowLink * _workoutDataFlowLink;
    NSDate * _workoutEndDate;
    NSArray * _workoutEvents;
    NSDate * _workoutStartDate;
}

@property (nonatomic, retain) HKWorkoutBuilderConfiguration *configuration;
@property (nonatomic, copy) NSDateInterval *dataInterval;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) NSMutableDictionary *metadata;
@property (nonatomic, retain) NSObject<OS_dispatch_queue> *queue;
@property (readonly) Class superclass;
@property (nonatomic, readonly) <HDWorkoutDataAccumulator> *workoutDataAccumulator;
@property (readonly) unsigned long long workoutDataDestinationState;
@property (readonly) HKDataFlowLink *workoutDataFlowLink;
@property (readonly, copy) NSUUID *workoutDataProcessorUUID;
@property (nonatomic, copy) NSDate *workoutEndDate;
@property (nonatomic, retain) NSArray *workoutEvents;
@property (nonatomic, copy) NSDate *workoutStartDate;

+ (Class)configurationClass;
+ (bool)finishAllDetachedWorkoutBuildersExcludingSessions:(id)arg1 profile:(id)arg2 error:(id*)arg3;
+ (bool)finishAllWorkoutBuildersForClient:(id)arg1 profile:(id)arg2 error:(id*)arg3;
+ (void)finishDetachedBuilderForEntity:(id)arg1 sessionEndDate:(id)arg2 profile:(id)arg3;
+ (id)recoveredWorkoutBuilderConfigurationForClient:(id)arg1 sessionIdentifier:(id)arg2 builderIdentifierOut:(id*)arg3 profile:(id)arg4 error:(id*)arg5;
+ (id)requiredEntitlements;
+ (id)taskIdentifier;
+ (bool)validateConfiguration:(id)arg1 error:(out id*)arg2;

- (void).cxx_destruct;
- (void)_activateIfNeededAndPerformOnQueue:(id /* block */)arg1 errorHandler:(id /* block */)arg2;
- (void)_discardWorkout;
- (void)_performIfActiveOrReadyOnQueue:(id /* block */)arg1 errorHandler:(id /* block */)arg2;
- (void)_performIfAuthorizedToSaveWorkoutOnQueue:(id /* block */)arg1 errorHandler:(id /* block */)arg2;
- (void)_performOnQueueIfState:(unsigned long long)arg1 block:(id /* block */)arg2 errorHandler:(id /* block */)arg3;
- (bool)_queue_addMetadata:(id)arg1 error:(id*)arg2;
- (void)_queue_addQuantityTypesIncludedWhilePausedFromSource:(id)arg1;
- (id)_queue_associateSamples:(id)arg1 transaction:(id)arg2 error:(id*)arg3;
- (void)_queue_attemptRequeryForInvalidatedStatisticsCalculators;
- (id)_queue_configurationForPersistenceWithError:(id*)arg1;
- (void)_queue_didChangeElapsedTimeBasis;
- (void)_queue_didUpdateEvents:(id)arg1;
- (void)_queue_didUpdateMetadata:(id)arg1;
- (void)_queue_didUpdateStatistics:(id)arg1;
- (void)_queue_endCollectionWithEndDate:(id)arg1 completion:(id /* block */)arg2;
- (void)_queue_failWithError:(id)arg1;
- (void)_queue_finishWorkoutWithCompletion:(id /* block */)arg1;
- (bool)_queue_insertWorkoutEvents:(id)arg1 error:(id*)arg2;
- (void)_queue_loadOrCreatePersistentEntity;
- (id)_queue_maskedIntervalsForStatisticsOfType:(id)arg1;
- (bool)_queue_persistDataSourceRecoveryDataInTransaction:(id)arg1 error:(id*)arg2;
- (void)_queue_persistRecoveryData;
- (bool)_queue_persistWorkoutEvents:(id)arg1 error:(id*)arg2;
- (void)_queue_recoverAssociatedSeriesBuilders;
- (void)_queue_recoverPersistedData;
- (void)_queue_setState:(unsigned long long)arg1;
- (id)_queue_sourceOrderProviderForQuantityType:(id)arg1;
- (id)_queue_statisticsCalculatorForQuantityType:(id)arg1;
- (id)_queue_statisticsDataSourceForQuantityType:(id)arg1;
- (void)_queue_updateCachedStateWithWorkoutEvents:(id)arg1;
- (void)_queue_updateStatisticsPauseResumeMask;
- (id)_queue_updateStatisticsWithQuantitySamples:(id)arg1 transaction:(id)arg2 error:(id*)arg3;
- (void)_saveSamples:(id)arg1 withCompletion:(id /* block */)arg2;
- (void)_setupDataSource:(id)arg1 identifier:(id)arg2;
- (void)addDataAccumulationObserver:(id)arg1;
- (void)addMetadata:(id)arg1 dataSource:(id)arg2;
- (void)addSampleObserver:(id)arg1;
- (void)addSamples:(id)arg1 dataSource:(id)arg2;
- (void)addWorkoutEvents:(id)arg1 dataSource:(id)arg2;
- (id)configuration;
- (void)connectionInvalidated;
- (id)currentEvents;
- (id)currentMetadata;
- (id)dataInterval;
- (id)description;
- (void)didCreateTaskServer:(id)arg1;
- (void)didInvalidateTaskServer:(id)arg1;
- (bool)enumerateSamplesOfType:(id)arg1 error:(id*)arg2 handler:(id /* block */)arg3;
- (id)exportedInterface;
- (id)initWithUUID:(id)arg1 configuration:(id)arg2 client:(id)arg3 profile:(id)arg4 delegate:(id)arg5;
- (id)metadata;
- (id)queue;
- (unsigned long long)queue_state;
- (id)remoteInterface;
- (void)remote_addDataSourcesWithIdentifiers:(id)arg1;
- (void)remote_addMetadata:(id)arg1 completion:(id /* block */)arg2;
- (void)remote_addSamples:(id)arg1 completion:(id /* block */)arg2;
- (void)remote_addWorkoutEvents:(id)arg1 completion:(id /* block */)arg2;
- (void)remote_beginCollectionWithStartDate:(id)arg1 completion:(id /* block */)arg2;
- (void)remote_discardWorkout;
- (void)remote_endCollectionWithEndDate:(id)arg1 completion:(id /* block */)arg2;
- (void)remote_finishWorkoutWithCompletion:(id /* block */)arg1;
- (void)remote_recoverWithCompletion:(id /* block */)arg1;
- (void)remote_removeDataSourcesWithIdentifiers:(id)arg1;
- (void)remote_updateDevice:(id)arg1;
- (void)removeDataAccumulationObserver:(id)arg1;
- (void)removeSampleObserver:(id)arg1;
- (void)setConfiguration:(id)arg1;
- (void)setDataInterval:(id)arg1;
- (void)setMetadata:(id)arg1;
- (void)setQueue:(id)arg1;
- (void)setWorkoutEndDate:(id)arg1;
- (void)setWorkoutEvents:(id)arg1;
- (void)setWorkoutStartDate:(id)arg1;
- (id)workoutDataAccumulator;
- (unsigned long long)workoutDataDestinationState;
- (id)workoutDataFlowLink;
- (id)workoutDataProcessorUUID;
- (id)workoutEndDate;
- (id)workoutEvents;
- (id)workoutStartDate;

@end
